# Generated by Django 3.2.3 on 2021-05-27 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(choices=[('HR', 'HR'), ('Infrastructures', 'Infrastructures'), ('IT services', 'IT services')], max_length=250)),
                ('designation', models.CharField(choices=[('Javascript Developer', 'Javascript Developer'), ('Python Developer', 'Python Developer'), ('PHP Developer', 'PHP Developer')], max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
            ],
        ),
    ]
